[package]
name = "model"
version = "0.1.0"
edition = "2021"

[lib]
name = "model"

[dependencies]
anyhow = { workspace = true }
near-sdk = { workspace = true }
async-trait = { workspace = true }
integration-trait = { workspace = true }
